version: 2
jobs:
  build:
    working_directory: ~/rest-service
    docker:
      - image: circleci/openjdk:8-jdk
    
    steps:
      - checkout
      - restore_cache:
          key: rest-service-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: rest-service-{{ checksum "pom.xml" }}
      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/rest-service.war